IepAuctions/IepAuctions/Models/SystemParameter.cs
namespace IepAuctions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SystemParameter
    {
        [Key]
        public int params_id { get; set; }

        [Required]
        [Range(0, 1000)]
        public int? auctions_per_page { get; set; }

        [Required]
        [Range(1, int.MaxValue)]
        public int? auctions_duration { get; set; }

        [Required]
        [StringLength(20)]
        public string currency { get; set; }

        [Required]
        [Range(0.0, Double.MaxValue)]
        public decimal? token_value { get; set; }

        [Required]
        [Range(1, int.MaxValue)]
        public int? tokens_silver { get; set; }

        [Required]
        [Range(1, int.MaxValue)]
        public int? tokens_gold { get; set; }

        [Required]
        [Range(1, int.MaxValue)]
        public int? tokens_platinum { get; set; }
    }
}

IepAuctions/IepAuctions/Controllers/SystemParametersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IepAuctions.Models;

namespace IepAuctions.Controllers
{
    public class SystemParametersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SystemParameters
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.SystemParameters.ToList().First());
        }

        // GET: SystemParameters/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SystemParameter systemParameter = db.SystemParameters.Find(id);
            if (systemParameter == null)
            {
                return HttpNotFound();
            }
            return View(systemParameter);
        }

        // POST: SystemParameters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "params_id,auctions_per_page,auctions_duration,currency,token_value,tokens_silver,tokens_gold,tokens_platinum")] SystemParameter systemParameter)
        {
            string errorMessage = "";
            bool canModify = true;
            if (ModelState.IsValid)
            {
                if (systemParameter.tokens_silver >= systemParameter.tokens_gold) {
                    errorMessage += "Number of tokens for Golden pack must be greater than number of tokens for Silver pack!<br>";
                    canModify = false;
                }

                if (systemParameter.tokens_silver >= systemParameter.tokens_platinum) {
                    errorMessage += "Number of tokens for Platinum pack must be greater than number of tokens for Silver pack!<br>";
                    canModify = false;
                }

                if (systemParameter.tokens_gold >= systemParameter.tokens_platinum) {
                    errorMessage += "Number of tokens for Platinum pack must be greater than number of tokens for Golden pack!<br>";
                    canModify = false;
                }

                if(canModify == true)
                {
                    db.Entry(systemParameter).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorMessage = errorMessage + "<br>";
                    return View(systemParameter);
                }
            }


            return View(systemParameter);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IepAuctions/IepAuctions/Views/SystemParameters/Edit.cshtml
@model IepAuctions.Models.SystemParameter

@{
    ViewBag.Title = "Edit";
}

<h2>Edit System Parameters</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="text-danger">@Html.Raw(ViewBag.ErrorMessage)</div>
        @Html.HiddenFor(model => model.params_id)

        <div class="form-group">
            @Html.LabelFor(model => model.auctions_per_page, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.auctions_per_page, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.auctions_per_page, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.auctions_duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.auctions_duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.auctions_duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.currency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.currency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.currency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.token_value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.token_value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.token_value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tokens_silver, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tokens_silver, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tokens_silver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tokens_gold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tokens_gold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tokens_gold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tokens_platinum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tokens_platinum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tokens_platinum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IepAuctions/IepAuctions/Views/SystemParameters/Index.cshtml
@model IepAuctions.Models.SystemParameter

@{
    ViewBag.Title = "Index";
}

<h2>System Parameters</h2>
<br />

<div class="row">
    <div class="col-sm-4">
        <table class="table">
            <tr>
                <th>Auctions Per Page</th>
                <td>@Model.auctions_per_page</td>
            </tr>
            <tr>
                <th>Auctions Default Duration</th>
                <td>@Model.auctions_duration</td>
            </tr>
            <tr>
                <th>Portal Currency</th>
                <td>@Model.currency</td>
            </tr>
            <tr>
                <th>Token Value</th>
                <td>@Model.token_value</td>
            </tr>
            <tr>
                <th>Tokens For Silver Package</th>
                <td>@Model.tokens_silver</td>
            </tr>
            <tr>
                <th>Tokens For Gold Package</th>
                <td>@Model.tokens_gold</td>
            </tr>
            <tr>
                <th>Tokens For Platinum Package</th>
                <td>@Model.tokens_platinum</td>
            </tr>
        </table>
    </div>
</div>


<a href="@Url.Action("Edit", "SystemParameters", new { id = Model.params_id })" class="btn btn-primary">
    <i class="fas fa-cog"></i>
    Edit
</a>