IepAuctions/IepAuctions/Models/TokenOrder.cs
namespace IepAuctions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TokenOrder")]
    public partial class TokenOrder
    {
        [Key]
        public Guid order_id { get; set; }

        public int? num_of_tokens { get; set; }

        public decimal? packet_price { get; set; }

        [StringLength(100)]
        public string packet_name { get; set; }

        public int? order_status { get; set; }

        public DateTime? date_created { get; set; }

        public DateTime? date_confirmed { get; set; }

        [Required]
        [StringLength(128)]
        public string user_id { get; set; }
    }
}

IepAuctions/IepAuctions/Models/TokenOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IepAuctions.Models
{
    public class TokenCreate
    {
        public string package_type { set; get; }
    }

    public partial class TokenOrderViewModel
    {
        [Key]
        public Guid order_id { get; set; }

        public int? num_of_tokens { get; set; }

        public decimal? packet_price { get; set; }

        [StringLength(100)]
        public string packet_name { get; set; }

        public int? order_status { get; set; }

        public DateTime? date_created { get; set; }

        public DateTime? date_confirmed { get; set; }

    }
}

IepAuctions/IepAuctions/Controllers/TokenOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using IepAuctions.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using PagedList;

namespace IepAuctions.Controllers
{
    public class TokenOrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: TokenOrders
        [Authorize(Roles = "User,Admin")]
        public ActionResult Index(int? page)
        {
            string user_id = User.Identity.GetUserId();
            var orders = from o in db.TokenOrders
                         where o.user_id == user_id
                         select new TokenOrderViewModel
                         {
                             order_id = o.order_id,
                             num_of_tokens = o.num_of_tokens,
                             packet_price = o.packet_price,
                             packet_name = o.packet_name,
                             order_status = o.order_status,
                             date_created = o.date_created,
                             date_confirmed = o.date_confirmed
                         };

            orders = orders.OrderByDescending(o => o.date_created);
            int pageSize = (int)db.SystemParameters.First().auctions_per_page;
            int pageNumber = (page ?? 1);
            return View(orders.ToPagedList(pageNumber, pageSize));
        }


        [HttpGet]
        [AllowAnonymous]
        public HttpStatusCodeResult CentiliPayment(string clientid, string status, int amount)
        {
            Guid guidOrder = new Guid(clientid);
            var order = db.TokenOrders.Find(guidOrder);
            if (order == null || order.order_status != 0) return new HttpStatusCodeResult(406);

            order.date_confirmed = DateTime.UtcNow;
            bool goodAmount = amount == (int)order.num_of_tokens;
            if (status == "success" &&  goodAmount)
            {
                order.order_status = 2;
                var user = db.Users.Find(order.user_id);

                user.Tokens += (int)order.num_of_tokens;
                db.SaveChanges();

                //slanje mejla
                var msg = new MailMessage();
                msg.To.Add(new MailAddress(user.Email));
                msg.From = new MailAddress("iep.etf.2018@gmail.com");

                msg.Subject = "Aucitons Portal - Token Order";
                msg.Body = "You have successfully purchased " + order.num_of_tokens + " tokens!";

                SmtpClient smtp = new SmtpClient("smtp.gmail.com");
                smtp.Port = 587;
                smtp.Credentials = new NetworkCredential("iep.etf.2018@gmail.com", "iepetf2018");
                smtp.EnableSsl = true;
                smtp.Send(msg);
                logger.Info("Order " + order.order_id + " - successfull purchase");
            }
            else
            {
                logger.Info("Order " + order.order_id + " canceled");
                order.order_status = 1;
                db.SaveChanges();
                return new HttpStatusCodeResult(406);
            }


            return new HttpStatusCodeResult(200);
        }



        //// GET: TokenOrders/Details/5
        //public ActionResult Details(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    if (tokenOrder == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tokenOrder);
        //}

        // GET: TokenOrders/Create
        [Authorize(Roles = "User,Admin")]
        public ActionResult Create()
        {
            SystemParameter sp = db.SystemParameters.First();
            ViewBag.TokensSilver = sp.tokens_silver;
            ViewBag.TokensGold = sp.tokens_gold;
            ViewBag.TokensPlatinum = sp.tokens_platinum;
            ViewBag.TokenValue = sp.token_value;
            var uid = User.Identity.GetUserId();
            var user = db.Users.Where(u => u.Id == uid).First();
            ViewBag.Tokens = user.Tokens;
            return View();
        }

        // POST: TokenOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Admin")]
        public ActionResult Create([Bind(Include = "package_type")] TokenCreate tokenCreate)
        {
            if (ModelState.IsValid)
            {
                TokenOrder order = new TokenOrder();
                SystemParameter sysParams = db.SystemParameters.First(); 

                order.order_id = Guid.NewGuid();
                order.date_created = DateTime.UtcNow;
                order.order_status = 0;

                order.user_id = User.Identity.GetUserId();
                order.packet_name = tokenCreate.package_type;


                if(tokenCreate.package_type == "SILVER")
                {
                    order.packet_price = 22;
                    order.num_of_tokens = sysParams.tokens_silver;
                }
                else if(tokenCreate.package_type == "GOLD")
                {
                    order.packet_price = 30;
                    order.num_of_tokens = sysParams.tokens_gold;
                }
                else if(tokenCreate.package_type == "PLATINUM")
                {
                    order.packet_price = 40;
                    order.num_of_tokens = sysParams.tokens_platinum;
                }


                db.TokenOrders.Add(order);
                db.SaveChanges();

                int amount = (int)order.packet_price;
                string baseUrl = "http://stage.centili.com/payment/widget?apikey=f8428e6e027977fcf9762a2ff9f822c2&country=rs";
                string parameters = "&reference=" + order.order_id + "&price=" + amount;
                return Redirect(baseUrl + parameters);
                //string baseUrl = "http://stage.centili.com/widget/WidgetModule?api=f8428e6e027977fcf9762a2ff9f822c2";
                //string parameters = "&clientId=" + order.order_id + "&item_name=" + order.packet_name + "&country=rs&countrylock=true&amount=" + amount;
                //return Redirect(baseUrl + parameters);
            }

            return View(tokenCreate);
        }

        //// GET: TokenOrders/Edit/5
        //public ActionResult Edit(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    if (tokenOrder == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tokenOrder);
        //}

        //// POST: TokenOrders/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "order_id,num_of_tokens,packet_price,packet_name,order_status,date_created,date_confirmed,user_id")] TokenOrder tokenOrder)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(tokenOrder).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(tokenOrder);
        //}

        //// GET: TokenOrders/Delete/5
        //public ActionResult Delete(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    if (tokenOrder == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tokenOrder);
        //}

        //// POST: TokenOrders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(Guid id)
        //{
        //    TokenOrder tokenOrder = db.TokenOrders.Find(id);
        //    db.TokenOrders.Remove(tokenOrder);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IepAuctions/IepAuctions/Views/TokenOrders/Create.cshtml
@model IepAuctions.Models.TokenCreate

@{
    ViewBag.Title = "Create";
}

<h2>Buy Tokens</h2>
<hr />
<h4>Tokens: @ViewBag.Tokens</h4>
<hr />
<h4>Choose Pack:</h4>
@{

}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            @using (Html.BeginForm("Create", "TokenOrders", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.RadioButtonFor(model => model.package_type, "SILVER", new { @checked = true }) <strong>SILVER</strong>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <strong><i class="fas fa-coins"></i> +@ViewBag.TokensSilver tokens</strong>
                    </div>
                    <div class="col-md-4">
                        <strong>22 RSD</strong>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.RadioButtonFor(model => model.package_type, "GOLD") <strong>GOLD</strong>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <strong><i class="fas fa-coins"></i> +@ViewBag.TokensGold tokens</strong>
                    </div>
                    <div class="col-md-4">
                        <strong>30 RSD</strong>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.RadioButtonFor(model => model.package_type, "PLATINUM") <strong>PLATINUM</strong>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <strong><i class="fas fa-coins"></i> +@ViewBag.TokensPlatinum tokens</strong>
                    </div>
                    <div class="col-md-4">
                        <strong>40 RSD</strong>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="submit" value="Create Order" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<br />
<br />

IepAuctions/IepAuctions/Views/TokenOrders/Delete.cshtml
@model IepAuctions.Models.TokenOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TokenOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.num_of_tokens)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_of_tokens)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.packet_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.packet_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.packet_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.packet_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order_status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_confirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_confirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IepAuctions/IepAuctions/Views/TokenOrders/Details.cshtml
@model IepAuctions.Models.TokenOrder

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TokenOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.num_of_tokens)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_of_tokens)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.packet_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.packet_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.packet_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.packet_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order_status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_confirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_confirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.order_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IepAuctions/IepAuctions/Views/TokenOrders/Edit.cshtml
@model IepAuctions.Models.TokenOrder

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TokenOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.order_id)

        <div class="form-group">
            @Html.LabelFor(model => model.num_of_tokens, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num_of_tokens, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num_of_tokens, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.packet_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.packet_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.packet_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.packet_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.packet_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.packet_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.order_status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.order_status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.order_status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_confirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_confirmed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_confirmed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IepAuctions/IepAuctions/Views/TokenOrders/Index.cshtml
@model PagedList.IPagedList<IepAuctions.Models.TokenOrderViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<h2>Token Orders</h2>

<p>
    <a href="@Url.Action("Create", "TokenOrders")" class="btn btn-default">
        <i class="fas fa-shopping-cart"></i>
        Buy Tokens
    </a>
</p>
<br />
<table class="table">
    <tr>
        <th>
            Order Id
        </th>
        <th>
            Tokens
        </th>
        <th>
            Package Price
        </th>
        <th>
            Package Type
        </th>
        <th>
            Order Status
        </th>
        <th>
            Time Created
        </th>
        <th>
            Time Confirmed
        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.order_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.num_of_tokens)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.packet_price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.packet_name)
        </td>
        <td>
            @{
                string[] arr = { "SUBMITTED", "CANCELED", "COMPLETED" };
                string order_status = arr[(int)item.order_status];
            }
            @order_status
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date_created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date_confirmed)
        </td>
    </tr>
    }

</table>
<br />


@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

IepAuctions/IepAuctions/Views/TokenOrders/PaymentResult.cshtml
@{
    ViewBag.Title = "PaymentResult";
}

<h2>PaymentResult: @ViewBag.Message</h2>