IepAuctions/IepAuctions/Models/Auction.cs
namespace IepAuctions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Auction")]
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            Bids = new HashSet<Bid>();
        }

        [Key]
        public Guid auction_id { get; set; }

        [StringLength(100)]
        public string product_name { get; set; }

        public byte[] product_image { get; set; }

        public int? duration { get; set; }

        public int? start_price { get; set; }

        public int? current_price { get; set; }

        public DateTime? date_created { get; set; }

        public DateTime? date_opened { get; set; }

        public DateTime? date_closed { get; set; }

        public int? status { get; set; }

        [StringLength(128)]
        public string last_bidder { get; set; }

        [StringLength(20)]
        public string currency { get; set; }

        public decimal? token_value { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }
    }
}

IepAuctions/IepAuctions/Models/AuctionViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IepAuctions.Models
{
    public partial class AuctionSearch
    {
        public Guid auction_id { get; set; }

        public string product_name { get; set; }

        public byte[] product_image { get; set; }

        public int? duration { get; set; }

        public int? start_price { get; set; }

        public int? current_price { get; set; }

        public DateTime? date_created { get; set; }

        public DateTime? date_opened { get; set; }

        public int? status { get; set; }

        public string last_bidder { get; set; }

        public string currency { get; set; }

        public decimal? token_value { get; set; }
    }

    public partial class AuctionCreate
    {
        //public int ID { get; set; }

        [Required]
        [Display(Name = "Product name")]
        public string product_name { get; set; }

        [Display(Name = "Duration(seconds)")]
        [Range(5, int.MaxValue)]
        public int? duration { get; set; }

        [Required]
        [Display(Name = "Starting price")]
        [Range(0, int.MaxValue)]
        public int start_price { get; set; }


        [Required]
        [Display(Name = "Image")]
        public HttpPostedFileBase ImageToUpload { get; set; }

    }
}

IepAuctions/IepAuctions/Controllers/AuctionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IepAuctions.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using Hangfire;
using System.Data.Entity.Infrastructure;

namespace IepAuctions.Controllers
{
    public class AuctionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Auctions
        public ActionResult Index(String searchString, string auctionStatus, int? minPrice, int? maxPrice, int? page)
        {
            ViewBag.searchString = null;
            ViewBag.minPrice = null;
            ViewBag.maxPrice = null;
            ViewBag.auctionStatus = "-1";

            var auctions = from a in db.Auctions
                           select new AuctionSearch
                           {
                               auction_id = a.auction_id,
                               product_name = a.product_name,
                               product_image = a.product_image,
                               duration = a.duration,
                               start_price = a.start_price,
                               current_price = a.current_price,
                               status = a.status,
                               date_created = a.date_created,
                               date_opened = a.date_opened,
                               last_bidder = a.last_bidder,
                               currency = a.currency,
                               token_value = a.token_value
                           };

            if (!String.IsNullOrEmpty(searchString))
            {
                var strings = searchString.Split(' ');
                auctions = auctions.Where(a => strings.Any(val => a.product_name.Contains(val)));
                ViewBag.searchString = searchString;
            }

            if (auctionStatus != null && auctionStatus != "-1")
            {
                ViewBag.auctionStatus = auctionStatus;
                auctions = auctions.Where(a => auctionStatus == a.status.ToString());
            }

            if (minPrice != null)
            {
                ViewBag.minPrice = minPrice;
                auctions = auctions.Where(a => a.current_price >= minPrice);
            }

            if (maxPrice != null)
            {
                ViewBag.maxPrice = maxPrice;
                auctions = auctions.Where(a => a.current_price <= maxPrice);
            }

            auctions = auctions.OrderByDescending(a => a.date_created);

            int pageSize = (int)db.SystemParameters.First().auctions_per_page;
            int pageNumber = (page ?? 1);
            return View(auctions.ToPagedList(pageNumber, pageSize));
        }

        //GET: Auctions/WonAuctions
        [Authorize(Roles = "Admin,User")]
        public ActionResult WonAuctions(int? page)
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.First(u => u.Id == userId);

            var auctions = from a in db.Auctions
                           where a.last_bidder == userId
                           where a.status == 2
                           select new AuctionSearch
                           {
                               auction_id = a.auction_id,
                               product_name = a.product_name,
                               product_image = a.product_image,
                               duration = a.duration,
                               start_price = a.start_price,
                               current_price = a.current_price,
                               status = a.status,
                               date_created = a.date_created,
                               date_opened = a.date_opened,
                               last_bidder = a.last_bidder,
                               currency = a.currency,
                               token_value = a.token_value
                           };

            auctions = auctions.OrderByDescending(a => a.date_created);

            int pageSize = (int)db.SystemParameters.First().auctions_per_page;
            int pageNumber = (page ?? 1);
            return View(auctions.ToPagedList(pageNumber, pageSize));
        }

        // GET: Auctions/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }

            return View(auction);
        }


        // GET: Auctions/Create
        [Authorize(Roles = "User,Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="User,Admin")]
        public ActionResult Create(AuctionCreate auctionData)
        {
            if (ModelState.IsValid)
            {
                Auction auction = new Auction();
                auction.auction_id = Guid.NewGuid();
                auction.product_name = auctionData.product_name;
                auction.start_price = auctionData.start_price;
                auction.current_price = auctionData.start_price;

                auction.date_created = DateTime.UtcNow;
                auction.status = 0; //READY

                auction.product_image = new byte[auctionData.ImageToUpload.ContentLength];
                auctionData.ImageToUpload.InputStream.Read(auction.product_image, 0, auction.product_image.Length);

                SystemParameter sysParam = db.SystemParameters.First();
                auction.currency = sysParam.currency;
                auction.token_value = sysParam.token_value;

                if (auctionData.duration == null) auction.duration = sysParam.auctions_duration;
                else auction.duration = auctionData.duration;

                db.Auctions.Add(auction);

                try
                {
                    db.SaveChanges();
                }
                catch(DbEntityValidationException ex)
                {
                    foreach (var EntityValidationErrors in ex.EntityValidationErrors)
                    {
                        foreach(var validatinoError in EntityValidationErrors.ValidationErrors)
                        {
                            Response.Write("property: " + validatinoError.PropertyName + " error: " + validatinoError.ErrorMessage);
                        }
                    }

                    return View();
                }


                logger.Info("Created auction " + auction.auction_id);
                return RedirectToAction("Details", new { id = auction.auction_id });
            }

            return View(auctionData);
        }

        //public ActionResult Create([Bind(Include = "auction_id,product_name,product_image,duration,start_price,current_price,date_created,date_opened,date_closed,status,last_bidder")] Auction auction)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        auction.auction_id = Guid.NewGuid();
        //        db.Auctions.Add(auction);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(auction);
        //}


        //// GET: Auctions/Edit/5
        //public ActionResult Edit(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Auction auction = db.Auctions.Find(id);
        //    if (auction == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(auction);
        //}

        //// POST: Auctions/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "auction_id,product_name,product_image,duration,start_price,current_price,date_created,date_opened,date_closed,status,last_bidder")] Auction auction)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(auction).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(auction);
        //}

        //// GET: Auctions/Delete/5
        //public ActionResult Delete(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Auction auction = db.Auctions.Find(id);
        //    if (auction == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(auction);
        //}

        //// POST: Auctions/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(Guid id)
        //{
        //    Auction auction = db.Auctions.Find(id);
        //    db.Auctions.Remove(auction);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        // GET: Auctions/OpenAuction/5
        [System.Web.Mvc.Authorize(Roles = "Admin")]

IepAuctions/IepAuctions/Views/Shared/DisplayTemplates/Auction.cshtml
@model IepAuctions.Models.Auction
@{
    ViewBag.Title = "Auction";
}



<div class="col-md-3">
    <div class="panel panel-primary">
        <div class="panel-heading text-center" style="min-height: 50px; max-height: 50px;">
            <h3 class="panel-title">
                <a href='@Url.Action("Details", "Auctions", new { id = Model.auction_id })'> <strong>@Html.DisplayFor(modelItem => Model.product_name)</strong></a>
            </h3>
        </div>
        <div class="panel-body text-center" style="min-height: 250px; max-height: 250px;">
            <div class="auction-image" style="min-height: 100px; max-height: 100px; position: relative">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.product_image)" />
            </div>
            @{
                string timeStr;
                TimeSpan time = TimeSpan.FromSeconds((double)Model.duration);
                if (Model.status == 0)//ready
                {
                    timeStr = time.ToString(@"hh\:mm\:ss");
                    if (time.TotalDays >= 1)
                    {
                        timeStr = timeStr.Substring(2);
                        timeStr = (time.Days * 24 + time.Hours).ToString() + timeStr;

                    }
                }
                else if (Model.status == 1) //opened
                {
                    TimeSpan timeLeft = (DateTime)Model.date_opened + time - DateTime.UtcNow;
                    if (timeLeft.TotalSeconds < 0)
                    {
                        timeStr = "00:00:00";
                    }
                    else
                    {
                        timeStr = timeLeft.ToString(@"hh\:mm\:ss");
                        if (time.TotalDays >= 1)
                        {
                            timeStr = timeStr.Substring(2);
                            timeStr = (time.Days * 24 + time.Hours).ToString() + timeStr;

                        }
                    }
                }
                else //completed
                {
                    timeStr = "00:00:00";
                }

                string lastBidder;
                if (String.IsNullOrEmpty(Model.last_bidder)) //no bids
                {
                    lastBidder = "No Bids Yet";
                }
                else
                {
                    var db = new IepAuctions.Models.ApplicationDbContext();
                    var user = db.Users.Find(Model.last_bidder);
                    lastBidder = user.UserName;
                }

                string scaledPrice = ((double)(Model.token_value * Model.current_price)).ToString("0.00");
                string price = Model.currency + " " + scaledPrice;
            }
            <br />
            <h4 id="auction_@Model.auction_id" style="font-weight: bold">@timeStr</h4>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8" id="auction_background_@Model.auction_id" style="padding: 5px 0;">
                    @if (Model.status == 1)
                    {
                        <strong id="auction_price_@Model.auction_id" class="text-success">@price</strong>
                        <strong id="auction_tokens_@Model.auction_id" class="text-success">(@Model.current_price</strong>
                        <strong id="auction_image_@Model.auction_id" class="text-success"><i class="fas fa-coins"></i>)</strong>
                    }
                    else
                    {
                        <strong id="auction_price_@Model.auction_id">@price</strong>
                        <strong id="auction_tokens_@Model.auction_id">(@Model.current_price</strong>
                        <strong id="auction_image_@Model.auction_id"><i class="fas fa-coins"></i>)</strong>
                    }
                </div>
            </div>
            <strong id="auction_bidder_@Model.auction_id">@lastBidder</strong>
        </div>
        <div class="panel-footer text-center">
            <div class="form-group">
                <input id="bid_tokens_@Model.auction_id" type="number" oninput="this.value = this.value.replace(/[^0-9]/g, '');" class="form-control" placeholder="Enter a Bid" style="min-width: 100%" />
                <input id="bid_current_@Model.auction_id" type="hidden" value="@Model.current_price" />
            </div>

            @if (Model.status == 0)
            {
                if (User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("OpenAuction", "Auctions", new { id = Model.auction_id })" class="btn btn-success btn-block">
                        <strong>Open Auction</strong>
                    </a>
                }
                else
                {
                    <button class="btn btn-default btn-block">
                        <strong>Ready</strong>
                    </button>
                }
            }
            else if (Model.status == 1)
            {
                <button id="bid_button_@Model.auction_id" class="btn btn-warning btn-block" onclick="sendBid('@Model.auction_id')">
                    <strong id="bid_text_@Model.auction_id">Bid Now</strong>
                </button>
            }
            else if (Model.status == 2)
            {
                <button id="bid_@Model.auction_id" class="btn btn-default btn-block" value="Bid">
                    <strong id="bid_text_@Model.auction_id">Ended</strong>
                </button>
            }
        </div>
    </div>
</div>

IepAuctions/IepAuctions/Views/Shared/DisplayTemplates/AuctionSearch.cshtml
@model IepAuctions.Models.AuctionSearch
@{
    ViewBag.Title = "Auction";
}



<div class="col-md-3">
    <div class="panel panel-primary">
        <div class="panel-heading text-center" style="min-height: 50px; max-height: 50px;">
            <h3 class="panel-title">
                <a href='@Url.Action("Details", "Auctions", new { id = Model.auction_id })'> <strong>@Html.DisplayFor(modelItem => Model.product_name)</strong></a>
            </h3>
        </div>
        <div class="panel-body text-center" style="min-height: 250px; max-height: 250px;">
            <div class="auction-image" style="min-height: 100px; max-height: 100px; position: relative">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.product_image)" />
            </div>
            @{
                string timeStr;
                TimeSpan time = TimeSpan.FromSeconds((double)Model.duration);
                if (Model.status == 0)//ready
                {
                    timeStr = time.ToString(@"hh\:mm\:ss");
                    if (time.TotalDays >= 1)
                    {
                        timeStr = timeStr.Substring(2);
                        timeStr = (time.Days * 24 + time.Hours).ToString() + timeStr;

                    }
                }
                else if (Model.status == 1) //opened
                {
                    TimeSpan timeLeft = (DateTime)Model.date_opened + time - DateTime.UtcNow;
                    if (timeLeft.TotalSeconds < 0)
                    {
                        timeStr = "00:00:00";
                    }
                    else
                    {
                        timeStr = timeLeft.ToString(@"hh\:mm\:ss");
                        if (time.TotalDays >= 1)
                        {
                            timeStr = timeStr.Substring(2);
                            timeStr = (time.Days * 24 + time.Hours).ToString() + timeStr;

                        }
                    }
                }
                else //completed
                {
                    timeStr = "00:00:00";
                }

                string lastBidder;
                if (String.IsNullOrEmpty(Model.last_bidder)) //no bids
                {
                    lastBidder = "No Bids Yet";
                }
                else
                {
                    var db = new IepAuctions.Models.ApplicationDbContext();
                    var user = db.Users.Find(Model.last_bidder);
                    lastBidder = user.UserName;
                }

                string scaledPrice = ((double)(Model.token_value * Model.current_price)).ToString("0.00");
                string price = Model.currency + " " + scaledPrice;
            }
            <br />
            <h4 id="auction_@Model.auction_id" style="font-weight: bold">@timeStr</h4>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8" id="auction_background_@Model.auction_id" style="padding: 5px 0;">
                    @if (Model.status == 1)
                    {
                        <strong id="auction_price_@Model.auction_id" class="text-success">@price</strong>
                        <strong id="auction_tokens_@Model.auction_id" class="text-success">(@Model.current_price</strong>
                        <strong id="auction_image_@Model.auction_id" class="text-success"><i class="fas fa-coins"></i>)</strong>
                    }
                    else
                    {
                        <strong id="auction_price_@Model.auction_id" >@price</strong>
                        <strong id="auction_tokens_@Model.auction_id" >(@Model.current_price</strong>
                        <strong id="auction_image_@Model.auction_id" ><i class="fas fa-coins"></i>)</strong>
                    }
                </div>
            </div>
            <strong id="auction_bidder_@Model.auction_id">@lastBidder</strong>
        </div>
        <div class="panel-footer text-center">
                    <div class="form-group">
                        <input id="bid_tokens_@Model.auction_id" type="number" oninput="this.value = this.value.replace(/[^0-9]/g, '');" class="form-control" placeholder="Enter a Bid" style="min-width: 100%"/>
                        <input id="bid_current_@Model.auction_id" type="hidden" value="@Model.current_price" />
                    </div>

            @if (Model.status == 0)
            {
                if (User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("OpenAuction", "Auctions", new { id = Model.auction_id })" class="btn btn-success btn-block">
                        <strong>Open Auction</strong>
                    </a>
                }
                else
                {
                    <button class="btn btn-default btn-block">
                        <strong>Ready</strong>
                    </button>
                }
            }
            else if (Model.status == 1)
            {
                <button id="bid_button_@Model.auction_id" class="btn btn-warning btn-block" onclick="sendBid('@Model.auction_id')">
                    <strong id="bid_text_@Model.auction_id">Bid Now</strong>
                </button>
            }
            else if (Model.status == 2)
            {
                <button id="bid_@Model.auction_id" class="btn btn-default btn-block" value="Bid">
                    <strong id="bid_text_@Model.auction_id">Ended</strong>
                </button>
            }
        </div>
    </div>
</div>